name: Forge tests

# Controls when the action will run. 
on:
  push:
    paths:
    - 'contracts/**/*.sol'

env:
  RPC_MAINNET: ${{ secrets.RPC_MAINNET }}

jobs:
  build:
    name: Yarn and foundry tests
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
        with:
          submodules: recursive


    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run tests
      run: forge test -vvv