name: Forge tests

# Controls when the action will run. 
on:
  push:
    paths:
    - 'contracts/**/*.sol'

env:
  RPC_MAINNET: ${{ secrets.RPC_MAINNET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Build
      run: forge build --sizes
      
    - name: Run tests
      run: forge test -vvv
